import type { Metadata } from "next";
import Link from "next/link";
import {
  Bot,
  BrainCircuit,
  FileCheck2,
  Layers,
  Search,
  ShieldCheck,
  Zap,
  ArrowRight,
  CheckCircle2,
  Database,
  BarChart3,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Features | BaseMind — Intelligence for Support & Knowledge",
  description:
    "Explore BaseMind's advanced RAG architecture, custom multi-agent orchestration, pgvector semantic search, and enterprise citation engine.",
};

const PILLARS = [
  {
    icon: BrainCircuit,
    tag: "Retrieval Architecture",
    title: "Precision Vector RAG Engine",
    description:
      "Powered by pgvector with HNSW index indexing. Embeddings are generated with state-of-the-art sentence transformers to ensure sub-millisecond semantic retrieval across thousands of pages.",
    benefits: [
      "HNSW cosine similarity indexing",
      "Dynamic chunking with overlap preserves context",
      "Metadata filtering by tenant and agent ID",
      "Context-window optimization for low-latency inference",
    ],
  },
  {
    icon: Bot,
    tag: "Agent Orchestration",
    title: "Multi-Agent System with Custom Tooling",
    description:
      "Deploy specialized agents for support, engineering documentation, onboarding, or sales. Each agent operates with customized instructions, system guardrails, and knowledge bindings.",
    benefits: [
      "Per-agent temperature and model configuration",
      "Instant toggle between active and dormant status",
      "Strict tenancy isolation preventing data leakage",
      "Custom system prompts tailored to brand voice",
    ],
  },
  {
    icon: FileCheck2,
    tag: "Universal Ingestion",
    title: "Automated Document Parsing & B2 Storage",
    description:
      "Drag and drop documents in PDF, TXT, CSV, or Markdown. Documents are securely saved in S3-compatible Backblaze B2 object storage and parsed into vector embeddings automatically.",
    benefits: [
      "Automated extraction pipeline with background workers",
      "Support for multi-page PDF documents & raw text files",
      "Live chunk inspector and embedding status tracking",
      "Instant document re-sync and vector deletion",
    ],
  },
  {
    icon: ShieldCheck,
    tag: "Reliability & Grounding",
    title: "Hallucination-Free Cited Answers",
    description:
      "Every answer generated by your agents includes explicit references and citation chips linking back to original verified documents, giving users 100% confidence.",
    benefits: [
      "Clickable source citations with snippet previews",
      "Confidence threshold pruning to eliminate guesswork",
      "Deterministic fallback when knowledge is unavailable",
      "Audit trail of every prompt and retrieved chunk",
    ],
  },
  {
    icon: BarChart3,
    tag: "Operations & Governance",
    title: "Full Telemetry & Audit Logs",
    description:
      "Gain full visibility into every user query, agent response latency, token consumption, and retrieval accuracy with our built-in logging and admin telemetry.",
    benefits: [
      "Request duration tracking with sub-millisecond precision",
      "Real-time operator alerts and platform health monitoring",
      "Complete conversation transcripts for quality control",
      "Role-based operator controls for platform administrators",
    ],
  },
  {
    icon: Zap,
    tag: "High Performance",
    title: "Streaming Responses & Real-Time Chat",
    description:
      "Engineered with FastAPI and modern Next.js for fluid typing animations and instant response times under 1.2 seconds.",
    benefits: [
      "Server-Sent Events (SSE) token streaming",
      "Responsive glassmorphism UI with dark mode support",
      "Razorpay payment infrastructure for instant upgrades",
      "Zero-downtime database migrations with Alembic",
    ],
  },
];

const WORKFLOW_STEPS = [
  {
    step: "01",
    title: "Upload Knowledge",
    detail: "Drop PDFs, release notes, or knowledge docs into your tenant base.",
    icon: Database,
  },
  {
    step: "02",
    title: "Vectorize & Index",
    detail: "Chunks are embedded and indexed into pgvector with strict tenant separation.",
    icon: Layers,
  },
  {
    step: "03",
    title: "Configure Agent",
    detail: "Set persona, instructions, tone, and select which knowledge to attach.",
    icon: Bot,
  },
  {
    step: "04",
    title: "Serve Answers with Citations",
    detail: "Users chat with answers strictly grounded in your verified facts.",
    icon: Sparkles,
  },
];

export default function FeaturesPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero */}
      <section className="relative overflow-hidden border-b bg-gradient-to-b from-primary/5 via-background to-background py-20">
        <div className="mx-auto max-w-5xl px-6 text-center">
          <Badge variant="outline" className="mb-4 gap-1.5 border-primary/40 text-primary">
            <Sparkles className="size-3.5" />
            Engineered for Enterprise Support
          </Badge>
          <h1 className="font-heading text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
            Supercharged AI Agents with{" "}
            <span className="text-primary">Retrieval Precision</span>
          </h1>
          <p className="mx-auto mt-5 max-w-2xl text-lg text-muted-foreground">
            BaseMind replaces static chatbots with context-aware, grounded AI agents
            anchored in your proprietary knowledge base.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
            <Button size="lg" asChild>
              <Link href="/signup">
                Start Free Trial <ArrowRight className="ml-2 size-4" />
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/pricing">Explore Pricing</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* How it Works Workflow */}
      <section className="py-20">
        <div className="mx-auto max-w-6xl px-6">
          <div className="text-center">
            <Badge variant="secondary" className="mb-2">How It Works</Badge>
            <h2 className="font-heading text-3xl font-bold tracking-tight">
              From Raw Documents to Conversational Intelligence
            </h2>
            <p className="mt-2 text-muted-foreground">
              A 4-step pipeline designed for zero hallucination and rapid deployment.
            </p>
          </div>

          <div className="mt-14 grid gap-6 md:grid-cols-4">
            {WORKFLOW_STEPS.map((w) => (
              <Card key={w.step} className="relative border bg-card/50 transition hover:border-primary/50">
                <CardContent className="p-6">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-2xl font-bold text-primary/70">{w.step}</span>
                    <w.icon className="size-6 text-primary" />
                  </div>
                  <h3 className="mt-4 font-heading text-lg font-semibold">{w.title}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">{w.detail}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Feature Deep Dive Grid */}
      <section className="border-t bg-muted/20 py-20">
        <div className="mx-auto max-w-6xl px-6">
          <div className="text-center">
            <Badge variant="secondary" className="mb-2">Deep Dive</Badge>
            <h2 className="font-heading text-3xl font-bold tracking-tight">
              Everything You Need for Mission-Critical AI
            </h2>
            <p className="mt-2 text-muted-foreground">
              Battle-tested architectural modules for production customer support and internal search.
            </p>
          </div>

          <div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {PILLARS.map((p) => (
              <Card key={p.title} className="flex flex-col border bg-card shadow-sm transition hover:shadow-md">
                <CardContent className="flex flex-1 flex-col p-6">
                  <div className="flex items-center gap-3">
                    <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <p.icon className="size-5" />
                    </div>
                    <Badge variant="outline" className="text-xs font-normal">
                      {p.tag}
                    </Badge>
                  </div>
                  <h3 className="mt-4 font-heading text-xl font-semibold">{p.title}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">{p.description}</p>
                  <div className="my-5 h-px bg-border" />
                  <ul className="mt-auto space-y-2 text-xs text-muted-foreground">
                    {p.benefits.map((b) => (
                      <li key={b} className="flex items-start gap-2">
                        <CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-primary" />
                        <span>{b}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="border-t py-20 text-center">
        <div className="mx-auto max-w-3xl px-6">
          <h2 className="font-heading text-3xl font-bold tracking-tight sm:text-4xl">
            Ready to deploy your first agent in under 2 minutes?
          </h2>
          <p className="mt-4 text-muted-foreground">
            Get started for free. No credit card required. Upgrade when your team scales.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4">
            <Button size="lg" asChild>
              <Link href="/signup">Get Started Free</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/pricing">View Pricing Plans</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
