import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — BaseMind",
  description:
    "The terms you agree to when you use the BaseMind AI SaaS platform.",
};

const SECTIONS: { h: string; body: string }[] = [
  {
    h: "Acceptance of terms",
    body: "By creating an account or using BaseMind, you agree to these terms. If you use BaseMind on behalf of an organization, you represent that you have authority to bind that organization to them.",
  },
  {
    h: "The service",
    body: "BaseMind lets you create custom AI support agents trained on your own uploaded files and web sources. You retain ownership of the content you upload; we license you nothing beyond the right to use the service.",
  },
  {
    h: "Your account",
    body: "You are responsible for keeping your credentials secure and for all activity under your account. You must provide accurate information and may not create accounts for automated or abusive purposes.",
  },
  {
    h: "Acceptable use",
    body: "You may not upload unlawful, infringing, or malicious content; probe or disrupt the service; siphon data at unreasonable rates; or use the service to generate unlawful or misleading output. We may suspend access that violates this section.",
  },
  {
    h: "AI output",
    body: "Agent responses are generated by large language models and may be inaccurate. The service is provided “as is” and you use agent output at your own discretion; do not rely on it for critical decisions without review.",
  },
  {
    h: "Intellectual property",
    body: "BaseMind and its branding belong to its owner. Your uploaded content remains yours, and we do not train shared AI models on your files.",
  },
  {
    h: "Limitation of liability",
    body: "To the maximum extent permitted by law, BaseMind is not liable for indirect, incidental, or consequential damages, or for lost data, arising from use of the service.",
  },
  {
    h: "Changes & contact",
    body: "We may update these terms; continued use after changes constitutes acceptance. Questions can be raised via the BaseMind GitHub repository (github.com/shivamsingh7533/BaseMind).",
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <Link
        href="/"
        className="text-sm font-medium text-primary hover:underline"
      >
        ← Back to home
      </Link>
      <h1 className="mt-4 font-heading text-3xl font-bold tracking-tight">
        Terms of Service
      </h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Last updated: September 2026
      </p>
      <div className="mt-8 space-y-8">
        {SECTIONS.map((s) => (
          <section key={s.h}>
            <h2 className="font-heading text-xl font-semibold">{s.h}</h2>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              {s.body}
            </p>
          </section>
        ))}
      </div>
    </div>
  );
}